
PUID="${PUID:-1000}"; export PUID
PGID="${PGID:-1000}"; export PGID

create_user()
{
    local errlevel

    if [ ! -d /noroot ]; then
        pw groupadd -n noroot -g "${PGID}" && \
        pw useradd -n noroot -d /noroot -u "${PUID}" -g "${PGID}"

        errlevel=$?

        if [ ${errlevel} -ne 0 ]; then
            return ${errlevel}
        fi

        mkdir -p /noroot || return $?
    fi

    chown noroot:noroot /noroot
}

warn()
{
    echo "##!> $* <!##"
}

err()
{
    echo "###> $* <###"
}

info()
{
    echo "======> $* <======"
}
