
PUID="${PUID:-1000}"; export PUID
PGID="${PGID:-1000}"; export PGID
UMASK="${UMASK:-0022}"; export UMASK
PUSER="noroot"
HOMEDIR=/noroot

umask -- "${UMASK}" || exit $?

set_homedir()
{
    if [ -z "$1" ]; then
        err "usage: set_homedir <directory>"
        exit 1
    fi

    HOMEDIR="$1"
}

create_user()
{
    local errlevel
    local username
    local homedir

    username=`_pw_usershow "${PUSER}" | cut -d: -f1` || return $?

    if [ "${username}" = "nouser" ]; then
        pw groupadd -n "${PUSER}" -g "${PGID}" && \
        pw useradd -n "${PUSER}" -d "${HOMEDIR}" -u "${PUID}" -g "${PGID}"

        errlevel=$?

        if [ ${errlevel} -ne 0 ]; then
            return ${errlevel}
        fi

        mkdir -p "${HOMEDIR}" || return $?
    fi

    # Maybe the home directory location has been updated.
    homedir=`_pw_usershow "${PUSER}" | cut -d: -f9` || return $?

    change_owner "${homedir:-${HOMEDIR}}"
}

change_owner()
{
    if [ -z "$1" ]; then
        err "usage: change_owner <file>"
        exit 1
    fi

    find -f "$1" \
        \( -fstype rdonly \) -o \
        \( ! \( -user "${PUID}" -group "${PGID}" \) \
            -exec chown "${PUID}:${PGID}" {} + \)
}

_pw_usershow()
{
    if [ -z "$1" ]; then
        err "usage: _pw_usershow <user>"
        exit 1
    fi

    pw usershow -Fn "$1"
}

warn()
{
    echo "##!> $*" >&2
}

err()
{
    echo "###> $*" >&2
}

info()
{
    echo "===> $*" >&2
}
